# Generated by Django 6.0.1 on 2026-03-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='subject_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
    ]
