# Generated by Django 6.0.1 on 2026-03-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_mark_subject_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
    ]
