# Generated by Django 6.0.1 on 2026-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subject'),
        ('teachers', '0004_teacher_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='students.subject'),
        ),
    ]
