# Generated by Django 6.0.1 on 2026-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
    ]
