# Generated by Django 6.0.1 on 2026-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
